insert into genre(genre_id, genre_category_id, name, registration_date) values 
(1, 1, 'Action', now()),
(2, 1, 'Adventure', now()),
(3, 1, 'Avant Garde', now()),
(4, 1, 'Award Winning', now()),
(5, 1, 'Comedy', now()),
(6, 1, 'Drama', now()),
(7, 1, 'Fantasy', now()),
(8, 1, 'Gourmet', now()),
(9, 1, 'Horror', now()),
(10, 1, 'Mistery', now()),
(11, 1, 'Romance', now()),
(12, 1, 'Sci-Fi', now()),
(13, 1, 'Slice of Life', now()),
(14, 1, 'Sports', now()),
(15, 1, 'Supernatural', now()),
(16, 1, 'Suspence', now()),
(17, 2, 'Ecchi', now()),
(18, 2, 'Erotica', now()),
(19, 2, 'Hentai', now()),
(20, 3, 'Adult Cast', now()),
(21, 3, 'Anthropomorphic', now()),
(22, 3, 'CGDCT', now()),
(23, 3, 'Childcare', now()),
(24, 3, 'Combat Sports', now()),
(25, 3, 'Crossdressing', now()),
(26, 3, 'Delinquents', now()),
(27, 3, 'Detective', now()),
(28, 3, 'Educational', now()),
(29, 3, 'Gag Humor', now()),
(30, 3, 'Gore', now()),
(31, 3, 'Harem', now()),
(32, 3, 'High Stakes Game', now()),
(33, 3, 'Historical', now()),
(34, 3, 'Idols (Female)', now()),
(35, 3, 'Idols (Male)', now()),
(36, 3, 'Isekai', now()),
(37, 3, 'Iyashikei', now()),
(38, 3, 'Love Polygon', now()),
(39, 3, 'Magical Sex Shift', now()),
(40, 3, 'Mahou Shoujo', now()),
(41, 3, 'Martial Arts', now()),
(42, 3, 'Mecha', now()),
(43, 3, 'Medical', now()),
(44, 3, 'Military', now()),
(45, 3, 'Music', now()),
(46, 3, 'Mythology', now()),
(47, 3, 'Organized Crime', now()),
(48, 3, 'Otaku Culture', now()),
(49, 3, 'Parody', now()),
(50, 3, 'Performing Arts', now()),
(51, 3, 'Pets', now()),
(52, 3, 'Psychological', now()),
(53, 3, 'Racing', now()),
(54, 3, 'Reincarnation', now()),
(55, 3, 'Reverse Harem', now()),
(56, 3, 'Romantic Subtext', now()),
(57, 3, 'Samurai', now()),
(58, 3, 'School', now()),
(59, 3, 'Showbiz', now()),
(60, 3, 'Space', now()),
(61, 3, 'Strategy Game', now()),
(62, 3, 'Super Power', now()),
(63, 3, 'Survival', now()),
(64, 3, 'Team Sports', now()),
(65, 3, 'Time Travel', now()),
(66, 3, 'Vampire', now()),
(67, 3, 'Video Game', now()),
(68, 3, 'Visual Arts', now()),
(69, 3, 'Workplace', now()),
(70, 4, 'Josei', now()),
(71, 4, 'Kids', now()),
(72, 4, 'Seinen', now()),
(73, 4, 'Shoujo', now()),
(74, 4, 'Shounen', now());

alter sequence genre_genre_id_seq restart with 74;